name: buildjet

on: [push, pull_request]

jobs:
  buildjet:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Test buildjet provider on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: ./
        with:
          workspaces: tests
          cache-provider: buildjet

      - run: |
          cargo check
          cargo test
          cargo build --release
        working-directory: tests
