name: simple

on: [push, pull_request]

jobs:
  simple:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Test `cargo check/test/build` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: ./
        with:
          workspaces: tests

      - run: |
          cargo check
          cargo test
          cargo build --release
        working-directory: tests
