name: target-dir

on: [push, pull_request]

jobs:
  target-dir:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Test custom target-dir on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - run: rustup toolchain install stable --profile minimal --no-self-update

      # the `workspaces` option has the format `$workspace -> $target-dir`
      # and the `$target-dir` is relative to the `$workspace`.
      - uses: ./
        with:
          workspaces: tests -> ../custom-target-dir

      - run: cargo test --manifest-path tests/Cargo.toml --target-dir custom-target-dir
